### ISSUE TITLE
Does this project accept contributions?

### ISSUE THREAD

**Issue by y4r9** [unitsml/schemas#9]
Since UnitsML is, or rather was, developed by NIST and later by an OASIS TC, I was wondering if this project would accept contributions or if it represents a locked down version of the standard? In the schemas I found the legal text from OASIS, stating that no changes can be made to the files. Please apologize if this is the wrong place to ask, but I was unable to find a definitive answer in the usual places. Thank you for your time and effort.

**Comment by ronaldtse** [comment]
@y4r9 UnitsML is now being continued under CalConnect's TC UNITS, the project would be happy to accept contributions externally of CalConnect.

We have not fully updated the schemas yet, so please feel free to submit PRs as desired. Thank you!

**Comment by y4r9** [comment]
Thank you very much for this information. That answers the question, therefore I would close this issue. Just one more follow up question. Is there a contribution guideline?

**Comment by ronaldtse** [comment]
We haven’t had the chance to update the guidelines yet, but it would be the typical standardization licensing where it is important for everyone to use the resulting work. Thanks!!
